# Generated by Django 4.2.4 on 2023-08-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='description',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
