# Generated by Django 4.2.4 on 2023-08-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
    ]
