# Generated by Django 4.2.4 on 2023-08-21 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_group_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 16, 20, 40, 754388)),
        ),
    ]
