# Generated by Django 4.2.4 on 2023-08-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_topic_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-createdAt']},
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date',
            new_name='createdAt',
        ),
    ]
