# Generated by Django 4.2.4 on 2023-08-21 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_topic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 6, 39, 14, 210389, tzinfo=datetime.timezone.utc)),
        ),
    ]
